### ISSUE TITLE
Support for single coordinates field

### ISSUE THREAD

**Issue by bmcbride** [mapbox/csv2geojson#16]
I'm trying to use csv2geojson with a standard CSV export from the [Memento Database](http://mementodatabase.com/) Android app. The export stores coordinates in a single field with the lat and long separated by a colon (42.719765710136365:-73.79929259419441). Is there any way to currently handle this? Thanks!

**Comment by tmcw** [comment]
Hm, not at the moment. Where do people come up with these bizarre latlng encodings...

**Comment by bmcbride** [comment]
Ha! Although a single coordinate field with a defined delimiter might not be that unusual of a scenario. The beauty of csv2geojson is that it allows you to take arbitrary data exports (from an asset management system for example) and easily incorporate them into a web map. Thanks for looking into it!

**Comment by tmcw** [comment]
Yeah... unfortunately it's not really possible to auto-detect and parse arbitrary encodings. I think I've got to make some kind of qualification here - maybe 'if it has a spec / documentation, or if it has 1M+ users, it's supported here' - otherwise it's a complexity bomb.

**Comment by bmcbride** [comment]
Understood. I'll just use a little PHP to handle this one: https://github.com/bmcbride/PHP-Database-GeoJSON/blob/master/simple_points/csv_points_geojson.php
