### ISSUE TITLE
magic separator detection fails on one-line files

### ISSUE THREAD

**Issue by tmcw** [mapbox/csv2geojson#19]

**Comment by springmeyer** [comment]
ha, been there too https://github.com/mapnik/mapnik/commit/affecb0f322824e9334670be0f27e61fb6e082ab#diff-39bb40e0a102095ff677dd3a15093b6d

**Comment by tmcw** [comment]
Was already fixed in 5dc2f42cd3373f258165e364463c80011c4d902e just needs a version bump.
