### ISSUE TITLE
longitude with exponents are misinterpreted

### ISSUE THREAD

**Issue by ziodave** [mapbox/csv2geojson#25]
I have a CSV such as the following

```
label,latitude,longitude
House,4.7161357378478E1,1.27381324768066E1
...
```

The output after conversion is:

```
    {
        "type": "Feature",
        "properties": {
            "label": "House"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [
                1.27381324768066,
                47.161357378478
            ]
        }
    }
```

As you can see the latitude is correctly interpreted, while the longitude sees its exponent dropped.

I traced down the issue being in lines 101-102 of `csv2geojson.js`:

```
        a = sexagesimal(lonk, 'EW');
        if (a) lonk = a;
```

`lonk` is turned from `1.27381324768066E1` to `1.27381324768066`.

**Comment by ziodave** [comment]
In [sexagesimal.js](https://github.com/mapbox/sexagesimal/blob/master/sexagesimal.js) `E` is most probably interpreted as cardinal direction.

**Comment by tmcw** [comment]
What kind of system outputs numbers formatted like this?

**Comment by ziodave** [comment]
Not sure, this is how data is provided to me.

**Comment by tmcw** [comment]
I don't think it's really possible to decipher between this case and people actually wanting 'east' coordinates: the input to csv2geojson should be either decimal numbers, or sexagesimal notation. Handling alternative forms of formatting for decimals will only make it ambiguous.

If your case, you can probably just find & replace E1 with nothing in the file.
