### ISSUE TITLE
fails to convert 1 mill rows of CSV data

### ISSUE THREAD

**Issue by ianhuynh** [mapbox/csv2geojson#52]
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

running from within OSX Terminal session on a 16GB RAM machine resulted in above error.  The CSV rows are simple with 4 columns:   Latitude,Longitude,GUID,16 char string

**Comment by tmcw** [comment]
Yep, 1 million rows is far beyond what this JavaScript tool will be able to process. You'll need to use a different piece of software, sorry.

**Comment by patdryburgh** [comment]
@tmcw Would it be possible to add a notice in the Readme file about what the limit is for this script? I was banging my head against the desk for about 20 min wondering why it couldn't process 36MM records.
