### ISSUE TITLE
sexagesimal dependency changed namespace

### ISSUE THREAD

**Issue by almereyda** [mapbox/csv2geojson#61]
Installing this module yields

    npm WARN deprecated sexagesimal@0.5.0: This module is now under the @mapbox namespace: install @mapbox/sexagesimal instead

This could be a very simple PR introducing the 8 characters they are asking for in front of the dependency into package.json

**Comment by andrewharvey** [comment]
Implemented by #59 and #62

**Comment by andrewharvey** [comment]
closed by https://github.com/mapbox/csv2geojson/commit/eb257b2d278e77333c5693b0bd5879d8d423dfdf
